spring:
  application:
    name: iLoveCoffee
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3307/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "1234"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate # 엔티티와 DB 테이블 구조 일치 여부 검증
    properties:
      hibernate:
        format_sql: true
    show-sql: false # logging.level 설정과 맞춰 필요시 조절

  # Flyway 마이그레이션 설정 추가
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Spring 기본 SQL 초기화 옵션은 Flyway 사용을 위해 제거/비활성화
  sql:
    init:
      mode: never

slack:
  webhook-url: ${SLACK_WEBHOOK_URL:https://hooks.slack.com/services/dummy/url}

logging:
  level:
    root: INFO
    # 우리 프로젝트 로그
    com.example.ilovecoffee: DEBUG

    # Hibernate가 실행한 SQL
    org.hibernate.SQL: OFF

    # SQL 파라미터 바인딩 값
    org.hibernate.orm.jdbc.bind: OFF

    # Flyway 초기화 및 실행 로그
    org.flywaydb: DEBUG

  pattern:
    # 콘솔용 로그 포맷
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%15.15t] %-40.40logger{36} : %msg%n"
    # 파일 저장용 콘솔 포맷
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %15.15t %-40.40logger{36} : %msg%n"

  # 로그 파일 생성 설정
  file:
    name: logs/application.log

  # 로그 파일 보관 설정
  logback:
    rollingpolicy:
      file-name-pattern: "logs/archived/%d{yyyy-MM-dd}.%i.log.gz"
      max-file-size: 10MB
      max-history: 300
      total-size-cap: 1GB

springdoc:
  swagger-ui:
    path: /swagger-ui.html

order:
  batch:
    cutoff-cron: "0 48 23 * * *"
    advance-delay-ms: 10000