spring:
  application:
    name: iLoveCoffee
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true # Flyway 우선 실행
    hibernate:
      ddl-auto: update # 엔티티와 DB 테이블 구조 일치 여부 검증
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  # 3. Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # 4. Spring 기본 SQL 초기화 비활성화 (Flyway 전용)
  sql:
    init:
      mode: never

# 5. Slack 환경 변수 및 기본값
slack:
  webhook-url: ${SLACK_WEBHOOK_URL:https://hooks.slack.com/services/dummy/url}

# 6. 관리자 인증 정보
admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin1234}

# 7. 로깅 설정
logging:
  level:
    root: INFO
    # 우리 프로젝트 로그
    com.example.ilovecoffee: DEBUG

    # Hibernate 실행 SQL (필요시 ON)
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF

    # Flyway 초기화 및 실행 로그
    org.flywaydb: DEBUG

  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%15.15t] %-40.40logger{36} : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %15.15t %-40.40logger{36} : %msg%n"

  file:
    name: logs/application.log

  logback:
    rollingpolicy:
      file-name-pattern: "logs/archived/%d{yyyy-MM-dd}.%i.log.gz"
      max-file-size: 10MB
      max-history: 300
      total-size-cap: 1GB

springdoc:
  swagger-ui:
    path: /swagger-ui.html

order:
  batch:
    cutoff-cron: "0 0 9 * * *"
    advance-delay-ms: 10000