spring:
  application:
    name: iLoveCoffee
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:menu.sql
        - classpath:menu_version.sql
        - classpath:order.sql
        - classpath:order_item.sql

logging:
  level:
    root: INFO
    # 우리 프로젝트 로그
    com.example.ilovecoffee: DEBUG

    # Hibernate가 실행한 SQL
    org.hibernate.SQL: OFF

    # SQL 파라미터 바인딩 값
    org.hibernate.orm.jdbc.bind: OFF

    # schema.sql, data.sql 초기화 로그
    org.springframework.jdbc.datasource.init: INFO

  pattern:
    # 콘솔용 로그 포맷
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%15.15t] %-40.40logger{36} : %msg%n"
    # 파일 저장용 콘솔 포맷
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %15.15t %-40.40logger{36} : %msg%n"

  # 로그 파일 생성 설정
  file:
    name: logs/application.log

  # 로그 파일 보관 설정
  logback:
    rollingpolicy:
      file-name-pattern: "logs/archived/%d{yyyy-MM-dd}.%i.log.gz"
      max-file-size: 10MB
      max-history: 300
      total-size-cap: 1GB

  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}


springdoc:
  swagger-ui:
    path: /swagger-ui.html

order:
  batch:
    cutoff-cron: "0 48 23 * * *"
    advance-delay-ms: 10000